### ISSUE TITLE
Minor accessibility issue with provided VioletPaginator component

### ISSUE THREAD

**Issue by markau** [sslotsky/violet-paginator#26]
The hyperlinks in the out-of-the-box `VioletPaginator` component could do with an aria-label to provide meaning. e.g. `<a aria-label="go to page 3">3</a>`

This is the only accessibility issue I'm seeing overall.

![image](https://cloud.githubusercontent.com/assets/3004849/23286585/a7fd70f6-fa88-11e6-80fb-117cfe16f2f2.png)

**Comment by sslotsky** [comment]
In truth, the fact that I'm using anchors at all is considered an accessibility issue. They should actually be buttons. I plan on making that change eventually but haven't gotten to it yet. I appreciate the suggestion and will make sure to keep `aria-label` in mind when I come back around to it. I confess they haven't been a huge priority because I see components as the smallest part of this library.

**Comment by markau** [comment]
It's minor really! Almost not worth posting. I'd rather say something than nothing though, and I learnt something out of it.
